### ISSUE TITLE
Сукааааааааааааа!!!!!! 

### ISSUE THREAD

**Issue by Fleut32** [shadowrun33/MT-spam-amino#4]
Как? Это? Скачать? На телефон?

**Comment by Fleut32** [comment]
Как этот код скачать на телефон? И что бы всë работало, а не выдавало по 100 ошибок😵😵😵

**Comment by shadowrun33** [comment]
да

**Comment by Fleut32** [comment]
Дак как его скачать то что бы работало? Есть туториал?

**Comment by shadowrun33** [comment]
Вбей в поиске Termux, поставь на него питон, гайды есть, надо просто поискать. Как ставить нужные библиотеки тоже можно без проблем найти.

**Comment by Fleut32** [comment]
А на телефоне сработает?

**Comment by Fleut32** [comment]
Я просто вообще во всëм этом чайник полный, мне бы пошаговую инструкцию как куда и что вбивать, а так я просто хочу поугарать над челиками в амино)

**Comment by Fleut32** [comment]
> 

А во всëм этом я вообще полны чайник

**Comment by shadowrun33** [comment]
Да, на телефон пойдёт, инструкции у меня увы нет, поищи, тебе надо узнать откуда и как поставить Termux, как туда установить Python и как сверху поставить библиотеки.

**Comment by Fleut32** [comment]
У меня питон версии 3.10.7 установился в термукс, а про библиотеки я не понял чутка(

**Comment by Fleut32** [comment]
Ща голова взорвётся от моего не понимания😱

**Comment by Fleut32** [comment]
Прошу тебя помоги мне пожалуйста!!! 🙏🙏🙏

**Comment by Fleut32** [comment]
У меня ошибка выскакивает когда я прокладываю путь к твоему коду пишет: Traceback (most recent call last):
  File "/storage/emulated/0/python1/main.py", line 1, in <module>
    import amino
ModuleNotFoundError: No module named 'amino'. Я вообще не понимаю что делать

**Comment by Fleut32** [comment]
Амино установлен у меня, а Termux  его найти не может когда я прописываю команду: "python main.py", а когда я пишу pip install -r requirements.txt, то мне вообще ошибку выдаëт

**Comment by Fleut32** [comment]
Админ помоги пожалуйста мнеее🙏

**Comment by Fleut32** [comment]
Блин вообще не выходит почему-то, я уже и так и сяк, а термкус ошибку выдаëт вечно(
